<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np

# Exercise 1 (Total recall) 

| **Term** | Brief description |
| :--- | :--- |
| Subsetting | To select a set of data from a larger set |
| Indexing | To select only one piece of data from a set |
| Slicing | To select a range of data from within a set |
| Masking | To 'hide' the result of indexing or slicing |

# Exercise 2 (Show me the ‘odd’ letters)

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [21]:
a = np_array_2d [:,0]
b = a.astype(int)
my_mask = b%2 > 0
print(np_array_2d [my_mask, 1])

['A' 'C' 'E' 'G' 'I']


# Exercise 3  

In [49]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
my_mask = np_array - 50 < 0
a = my_mask.astype(int)
my_mask2 = np_array - 50 > 0
b = my_mask2.astype(int)
print(-1 * a + b)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
