<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

* Subsetting means to select
* Indexing refers to selecting one element
* Slicing refers to selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [4]:
x = py_list

In [5]:
x = np_array

In [6]:
x[0]

np.str_('a1')

In [7]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [8]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [9]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [10]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [11]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [13]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [14]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [16]:
py_list_2d[3]
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [17]:
py_list_2d[3][0]
np_array_2d[3, 0]

np.str_('4')

In [18]:
py_list_2d[:3]
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [21]:
py_list_2d[:3][0]

[1, 'A']

In [20]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [22]:
py_list_2d[3:6][0]

[4, 'D']

In [23]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [39]:
np_array_2d[3:, 0]

array(['4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [25]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [43]:
x=[1]
print(x)
x= x + [2]
print(x)
x= x + [3]
print(x)
x= x + [4]
print(x)

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]


In [ ]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [30]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

# Some loose ends

## 1.5 Tuples

In [31]:
a=(1, 2, 3)     # Define tuple

In [32]:
print(a[0])    # Access data

1


In [33]:
# The following will NOT work
a[0]=-1

TypeError: 'tuple' object does not support item assignment

In [35]:
# The following will NOT work
a[0]+= [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [36]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [38]:
print(y)

[1, 2, 3]


In [37]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Footnotes