<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np


# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
py_real_names[0]


'Natasha Romanoff'

In [7]:
py_super_names[0]

'Black Widow'

In [8]:
py_super_names[2]    # Forward indexing 

'Doctor Strange'

In [9]:
                     # We need to know the size 
                     # beforehand for this to work.
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [11]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [12]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [22]:
py_superhero_info = [
    ['Natasha Romanoff', 'Black Widow'],
    ['Tony Stark', 'Iron Man'],
    ['Stephen Strange', 'Doctor Strange']
]

In [23]:
py_superhero_info[0]


['Natasha Romanoff', 'Black Widow']

# 2 Lists vs. Arrays

## 2.1 Size

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [16]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [24]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [25]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [26]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [31]:
np_array + 100

array([101, 102, 103, 104, 105])

In [32]:
py_list + 10        # Won't work!


TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [33]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [35]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [36]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [39]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [40]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [42]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [43]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [44]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [46]:
py_list == 3     # Works, but what IS the question?

False

In [47]:
np_array == 3  

array([False, False,  True, False, False])

In [48]:
np_array > 3  

array([False, False, False,  True,  True])

In [49]:
sum([False, False,  True, False, False])

1

In [50]:
sum(np_array > 3)

np.int64(2)

In [51]:
mask = np_array > 3
np_array[mask].sum()

np.int64(9)

## 2.8 Mathematics

In [52]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
sum(py_list)     # sum() is a base Python function

15

In [56]:
max(py_list)     # max() is a base Python function

5

In [57]:
min(py_list)     # min() is a base Python function

1

In [58]:
np_array.sum()

np.int64(15)

In [59]:
np_array.max()

np.int64(5)

In [60]:
np_array.min()

np.int64(1)

In [61]:
np_array.mean()

np.float64(3.0)

In [62]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes